### ISSUE TITLE
AsyncLogger closures memory leak on .NET core

### ISSUE THREAD

**Issue by raimana** [luigiberrettini/NLog.Targets.Syslog#180] opened 2019-02-26 08:49 UTC
For every message logged, a new instance of AsyncLogger is created and is never disposed & GC'd; the message string is also never disposed and GC'd since they are held by the AsyncLogger. Eventually the application run out of memory.

Is this behavior expected? Am I missing something? I'll start drilling down into SyslogTarget and AsyncLogger.

I've created a test project to replicate the issue: https://github.com/raimana/SyslogTest

1. Attach a profiler, add x number of messages
2. Collect a snapshot, inspect AsyncLogger instances (AsyncLogger.ProcessQueueAsync()) and String instances
3. Repeat this a few times.

Here's an example with 10 messages:
![asynclogger_instances](https://user-images.githubusercontent.com/6895151/53398292-2965c780-3a0e-11e9-8eb8-2760cc1570f9.PNG)

![string_instances](https://user-images.githubusercontent.com/6895151/53398305-2ec31200-3a0e-11e9-9682-a9a46f0611ee.PNG)

This is what I get from an application running for a few hours:
![asynclogger_instances](https://user-images.githubusercontent.com/6895151/53398028-83b25880-3a0d-11e9-853e-92e8aa3d81f2.PNG)

![string_instances](https://user-images.githubusercontent.com/6895151/53398641-f8d25d80-3a0e-11e9-8284-210be5938b7a.PNG)

NB: I was able to replicate this with 5.0.1, 5.1.0 & v6.0.0-beta

**Comment by luigiberrettini** [comment] 2019-02-26 11:34
I looked at you configuration and I saw that:

 - `<?xml version="1.0" encoding="utf-8"?>` is missing
 - you use `autoReload="true"` and it would be nice to see if removing it the issue doesn't show up
 - facility is not set `<facility>{facility}</facility>`
 - rfc is not set
 - server is not set `<server>{syslogserver}</server>`
 - port is not set `<port>{port}</port>`

> For every message logged, a new instance of AsyncLogger is created and is never disposed & GC'd

As you can see [here](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.0-beta-01/src/NLog.Targets.Syslog/SyslogTarget.cs#L55) AsyncLogger instances are created only on init and disposed only when [DisposeDependencies](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.0-beta-01/src/NLog.Targets.Syslog/SyslogTarget.cs#L104) is called
Moreover the buffer containing messages is created in the [AsyncLogger constructor](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.0-beta-01/src/NLog.Targets.Syslog/AsyncLogger.cs#L36) and disposed in the [Dispose](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.0-beta-01/src/NLog.Targets.Syslog/AsyncLogger.cs#L136), reusing it for all log entries that reach an AsyncLogger for performance reasons

**Comment by raimana** [comment] 2019-02-26 20:31
Ah the missing facility, server, port etc... In the nlog.config are just placeholder because I didn't want to advertise publicly my syslog server details.

I tried quickly without autoReload (and corrected the xml declaration), same behavior, these are the results, adding 50 message between each garbage collection (repeated 6 times).
![screen shot 2019-02-27 at 9 11 20 am](https://user-images.githubusercontent.com/6895151/53443203-05d36900-3a70-11e9-88ee-b2a4738d9e63.png)

**Comment by raimana** [comment] 2019-02-26 21:57
It's only happening on .net core, I've setup the same test using .net framework and I don't end up with an AsyncLogger instance for each messages sent, here's what I get when sending 50 messages 4 times.
![screen shot 2019-02-27 at 10 54 39 am](https://user-images.githubusercontent.com/6895151/53449319-6a95c000-3a7e-11e9-9a94-3694ffeaed82.png)

**Comment by raimana** [comment] 2019-02-27 08:00
I need to correct something, what I am observing is not an AsyncLogger instance per log entry, my test shows a single instance of AsyncLogger, `DisplayClass` are closure classes...

Might be barking up the wrong tree but they seem to be pinned by the CancellationTokenSource.
![capture](https://user-images.githubusercontent.com/6895151/53474670-9773c280-3ad2-11e9-987d-e8e44a733e39.PNG)

**Comment by luigiberrettini** [comment] 2019-02-27 09:43
> It's only happening on .net core

This is a big problem: I wrote code originally targeting the .NET framework, then also .NET Standard and if .NET Core behaves differently it breaks my main assumption

I could do the effort of rewriting everything with async await since it seems they do not plan to evolve classic TPL anymore, but this would probably drop support for old .NET framework versions and I really do not like that style also because it [needs to be adjusted](https://blogs.msdn.microsoft.com/seteplia/2018/10/01/the-danger-of-taskcompletionsourcet-class) by means of:
 - `ConfigureAwait(false)`
 - `Task.Yield`
 - `TaskCreationOptions.RunContinuationsAsynchronously`

**Comment by luigiberrettini** [comment] 2019-02-27 12:53
If you remove `, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Current` in `ProcessQueueAsync` probably you won't experience this issue

If this is confirmed the issue depends on how `ExecuteSynchronously` is handled and a small project reproducing this issue without using my library would be useful to open an issue on the CoreFX repo

If that change is needed the pipeline has to be review to guarantee atomicity the proper way

**Comment by raimana** [comment] 2019-02-27 18:43
> Does this [POC](https://github.com/luigiberrettini/tpl-memory-leak), whose results you can find below, cause the same issue to you?

It does, same issue.

> If you remove `, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Current` in `ProcessQueueAsync` probably you won't experience this issue

Indeed, once removed I no longer get these pinned closures.

**Comment by luigiberrettini** [comment] 2019-02-28 09:45
It would be great if you can check if you experience this issue in the [basic](https://github.com/luigiberrettini/tpl-memory-leak/tree/basic) and [trivial](https://github.com/luigiberrettini/tpl-memory-leak/tree/trivial) POC branches and can you post here the images related to your diagnostic sessions so that I can open an issue on CoreFX

**Comment by raimana** [comment] 2019-02-28 18:28
Sure, here it is, adding 50 messages between snapshots, repeated 9 times:
![screen shot 2019-03-01 at 7 23 46 am](https://user-images.githubusercontent.com/6895151/53588995-1d872a80-3bf3-11e9-9db8-a4eef7ecf9d5.png)

NB: I've made one minor change to the PoC, forcing a garbage collection at then end of the loop, i.e.  `GC.Collect()`.

**Comment by raimana** [comment] 2019-03-01 05:46
I ran another test that's a bit more intensive, adding 1 000 000 messages between snapshots:

**Basic**
![basic](https://user-images.githubusercontent.com/6895151/53617191-04aa6380-3c4b-11e9-8d7a-8242fc53efd7.png)


**Trivial**
![trivial](https://user-images.githubusercontent.com/6895151/53617199-0a07ae00-3c4b-11e9-965a-6787bba805a3.png)

Based on this, it doesn't seem to be an issue with TPL/.NET core, I suppose there's a threshold that must be reached before the GC collects objects stored on the heap.

I've also tried to run other tests (using NLog and NLog.Targets.Syslog) with and without the `connectionCheckTimeout` flag set to `100`, without it the output rate to the syslog server is pretty low (yes I've seen the historical discussions around it), messages are enqueued at a faster rate than they were dequeued.

Anyway, I need to run more tests, feel free to close this issue, I might re-open it once I've gathered enough data.

Cheers :-)

**Comment by luigiberrettini** [comment] 2019-03-01 12:17
> I've also tried to run other tests (using NLog and NLog.Targets.Syslog) with and without the `connectionCheckTimeout` flag set to `100`

Pay attention that connection check was causing a bug fixed with #164

To provide feedback on this issue please test only agains the latest 6.0.0 beta version so that if doesn't show up a release can be made

**Closed** 2019-03-05 08:58 UTC
Labels: question

**Comment by raimana** [comment] 2019-03-05 09:05
After running more tests and reviewing more memory dumps from our production server I found that what appeared to be a memory leak was in fact just the garbage collector being too greedy when in "Server" GC mode, over-allocating memory and holding onto objects a longer than expected, eventually consuming memory available.

I am satisfied that this had nothing to do with the Syslog Target.

Thanks for your help.

**Comment by luigiberrettini** [comment] 2019-03-05 09:59
Thank you!

It is always amazing to diagnose and troubleshoot 🤓
