### ISSUE TITLE
Is the target compatible with the new NLog extension configuration?

### ISSUE THREAD

**Issue by davidgeary** [luigiberrettini/NLog.Targets.Syslog#307] opened 2022-06-16 10:18 UTC
**Bug description**
Using the latest version of NLog (5.x), extension assemblies must now be explicitly specified, either via the `<extensions>` element or by suffixing the `type` property of the `<target>` element, as described in [PR 295](https://github.com/luigiberrettini/NLog.Targets.Syslog/pull/295#issue-1242114812).

However, when the `type` property is suffixed with the assembly name, a schema warning is displayed in Visual Studio.

Note that the warning does not prevent compilation (unless your project has `Treat warnings as errors` set to `true`).  Regardless, a workaround is to specify the assembly in the `<extensions>` element instead, rather than in the target's type.

**Expected behavior**
No warning to be displayed.

**Actual behavior**
A schema warning is displayed:

> The attribute 'type' has an invalid value 'sl:Syslog, NLog.Targets.Syslog' according to its schema type 'QName' - The ',' character, hexadecimal value 0x2C, cannot be included in a name.	

Visual Studio screenshot:

![nlog schema warning](https://user-images.githubusercontent.com/1843264/174046214-b121a055-d7cd-4a89-bdf7-b3d460d680c5.png)

**To reproduce**
1. Create an NLog configuration file, e.g. as per the [documentation example](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/master/docs/configuration.md#sample-configuration)
2. Remove the `<extensions>` element
3. Update the `<target>` element opening tag from:
``` xml
<target xsi:type="Syslog" name="cee-udp">
```
to
``` xml
<target xsi:type="Syslog, NLog.Targets.Syslog" name="cee-udp">
```

**Additional context**
 - NLog version: 5.0.1
 - NLog.Targets.Syslog version 7.0.0

**Comment by snakefoot** [comment] 2022-06-18 10:05
Looks like I was not thorough enough, when adding support for embedded assembly-name in type-alias. I liked the dotnet-syntax of specifying the assembly-name. But seems it is not compatible with QName-format.

Maybe adding support for assembly-name as QName-prefix like this:
```xml
<target xsi:type="NLog.Targets.Syslog:Syslog" name="cee-udp">
```
See also: https://github.com/NLog/NLog/pull/4979

**Comment by snakefoot** [comment] 2022-06-18 10:31
Curious is the XML Schema validation is still able to validate properties for the SysLog-target when using `NLog.Targets.Syslog:` as  prefix?

**Comment by snakefoot** [comment] 2022-06-18 11:20
@davidgeary In your example you use `xsi:type="sl:syslog"`, any reason why you include the `sl:`-prefix ?

**Comment by snakefoot** [comment] 2022-06-18 11:23
Maybe it comes from these examples:

https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/master/src/TestAppWithTUI/NLog.config
https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/master/src/TestAppWithGUI/NLog.config

Curious what is expected from `xsi:type="sl:syslog"` instead of just `xsi:type="syslog"` ?

**Comment by davidgeary** [comment] 2022-06-20 08:09
> In your example you use `xsi:type="sl:syslog"`, any reason why you include the `sl:`-prefix ?

The precise reason is lost in the mists of time, but best guess is that I just copied it from an example somewhere :-)

I've just tried replacing `sl:` with `NLog.Targets.Syslog:` in the `type` property and it works the same as long as the assembly is still included after the type name.  Just using the prefix without appending the assembly name fails to load it, but that's probably to be expected, since the `<target>` element is NLog-specific (rather than part of the XML std), so the format of the `type` property will surely need to conform to the formats supported by NLog?

AFAICS, the only place they mention the new capability of including the assembly name is in the list of [NLog 5.0 changes](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html):

> This means custom targets requires explicit &lt;add assembly="NLog.MyAssembly" /&gt;, or use the new ability to specify type with assembly-name: &lt;target type="MyTarget, NLog.MyAssembly" name="hello" /&gt;.

This would suggest that the assembly _must_ follow the type, separated by a comma.

(Was about to suggest getting clarification from NLog, but have just seen [the issue](https://github.com/NLog/NLog/issues/4978) you've raised, so will add a comment to that.)

**Comment by snakefoot** [comment] 2022-06-20 15:28
Thank you for confirming that intellisense also works for you when using prefix `NLog.Targets.Syslog:`. And also thank you for confirming that there is no clear reason for using `sl:` as prefix.

Now just need to decide if it should be NLog 5.0.2 or NLog 5.1 for using `xsi:type` qname-prefix as hint for assembly-loading (So XSD-intellisense will work together with assembly-loading-hint)

**Comment by luigiberrettini** [comment] 2022-06-21 16:25
> Curious what is expected from `xsi:type="sl:syslog"` instead of just `xsi:type="syslog"`?

The `sl:` prefix is used to comply with the [specifications](https://www.w3.org/TR/xmlschema-1/#Instance_Document_Constructions) by providing a [QName](https://en.wikipedia.org/wiki/QName) as the `xsi:type` attribute expects.

**Comment by luigiberrettini** [comment] 2022-06-21 16:26
Closing since the misbehavior is not caused by the target.

**Closed as completed by luigiberrettini** 2022-06-21 16:26 UTC
Labels: question

**Comment by snakefoot** [comment] 2022-06-21 16:32
> The sl: prefix is used to comply with the [specifications](https://www.w3.org/TR/xmlschema-1/#Instance_Document_Constructions) by providing a [QName](https://en.wikipedia.org/wiki/QName) as the xsi:type attribute expects.

Pretty sure the QName-prefix is optional.

**Comment by luigiberrettini** [comment] 2022-06-21 16:38
> Pretty sure the QName-prefix is optional

Yes, like for attribute names.
I just answered to clarify the doubts about its usage and to highlight the fact is has to be supported regardless of being optional or not.

**Comment by snakefoot** [comment] 2022-06-21 16:53
>  highlight the fact is has to be supported regardless of being optional or not.

Yes currently NLog puts a lot of effort into stripping away the prefix, so was just curious what benefit the prefix had.

Was maybe thinking to support this format `xsi:type="NLog.Targets.Syslog:Syslog"`, where NLog will use the prefix as Assembly-loading-hint.

**Comment by davidgeary** [comment] 2022-06-22 08:15
> Closing since the misbehavior is not caused by the target.

But this issue wasn't about the target specifically; it was to do with the XML schema, which identifies the new format as invalid.  (The original title of this issue was "XML schema warning issued when specifying extension assembly via target's type property".)

The warning incorrectly gives the impression that including the assembly name in the `type` property is invalid, when in reality, it is the schema that is wrong, since NLog no longer requires the `type` property to be a QName.

**Comment by snakefoot** [comment] 2022-06-22 16:52
> But this issue wasn't about the target specifically; it was to do with the XML schema, which identifies the new format as invalid.

The `xsi:type` is not part of the XML-Schema from NLog.xsd or NLog.Targets.Syslog.xsd.

The problem is not the XML-schema, but the NLog-team having broken the XSD-xsi-standard, by introducing a non-standard format which doesn't work with the `xsi:type`-attribute.

Guess we need more space-cowboys from the 2000's that knows XML / XSD  / XSLT by heart on the NLog-team, but until that happens, then we just have to go along with what we have, and repair as we go. See also https://github.com/NLog/NLog/pull/4979

**Comment by luigiberrettini** [comment] 2022-06-22 18:23
It seems from [Wikipedia](https://en.wikipedia.org/wiki/QName) that the [QName](https://www.oreilly.com/library/view/xml-in-a/0596007647/re157.html) syntax is `Prefix:LocalPart` where both Prefix and LocalPart are NCNames.

An [NCName](https://www.oreilly.com/library/view/xml-in-a/0596007647/re148.html) value follows these rules:
 - it does not contain a colon
 - it must consist exclusively of letters, digits, ideographs, underscores, hyphens, periods
 - it cannot start with a digit, an hyphen, the period

This means that NLog should support one of the two options below, where `sl:Syslog_NLog.Targets.Syslog` is just a possible choice to comply with NCName syntax.

**OPTION 1**
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
    <extensions>
        <add assembly="NLog.Targets.Syslog"/>
    </extensions>
    <targets>
        <target xsi:type="sl:Syslog" name="syslog-tgt">
            <!-- ... -->
        </target>
    </targets>
    <!-- ... -->
</nlog>
```

**OPTION 2**
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
    <targets>
        <target xsi:type="sl:Syslog_NLog.Targets.Syslog" name="syslog-tgt">
            <!-- ... -->
        </target>
    </targets>
    <!-- ... -->
</nlog>
```

**Comment by snakefoot** [comment] 2022-06-22 18:24
@luigiberrettini  Any reason why `xsi:type="NLog.Targets.Syslog:Syslog"` is bad ? (Since XSD-intellisense and XSD-validation will continue to work with that format)

**Comment by luigiberrettini** [comment] 2022-06-22 18:28
Because prefix should be an XML namespace declared in the file like `xsi` and `sl` and using `NLog.Targets.Syslog` as a prefix would not allow to specify the `sl` namespace.

In my opinion the goal should be both complying with specs and avoiding validation warnings/errors.

**Comment by snakefoot** [comment] 2022-06-22 18:30
When using `<target xsi:type="sl:Syslog_NLog.Targets.Syslog" name="syslog-tgt">` then XSD-intellisense and XSD-Validation stops working.

But with `xsi:type="NLog.Targets.Syslog:Syslog"` then everything is great. Again have no clue about what meaning the "prefix" has since it seems to be ignored by XSD-tooling.

**Comment by luigiberrettini** [comment] 2022-06-22 18:31
Ok then we need to find something that respects the specs and can be validated with a proper XML validator and then see if the Visual Studio validator works properly.

**Comment by snakefoot** [comment] 2022-06-22 18:33
What about `xsi:type="NLog.Targets.Syslog:Syslog"` ? (Again it is only an option that you can use, not something that is required if you like to use `<extensions>` instead)

**Comment by luigiberrettini** [comment] 2022-06-22 18:44
As I said that does not respects the specs.

Having as a goal to remove warnings will result in somebody else opening an issue because it is not XML compliant and not solving both is just saying, use another option, in which case this could have been the reply to this issue also.

**Comment by snakefoot** [comment] 2022-06-22 18:46
How does the QName-prefix `NLog.Targets.Syslog:` break the specs and the tooling ?

**Comment by luigiberrettini** [comment] 2022-06-22 18:47
As I wrote above the prefix must be an XML namespace and it is not.

I found out that `xsi:type="sl:Syslog_NLog.Targets.Syslog"` works but the NLog XSD needs to be changed: `sl:*` are identifiers looked up into the XSD.

**Comment by luigiberrettini** [comment] 2022-06-22 18:52
The best solution would be to use the power of XML adding an `assembly` optional attribute:

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sl="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
    <targets>
        <target xsi:type="sl:Syslog" assembly="NLog.Targets.Syslog" name="syslog-tgt">
            <!-- ... -->
        </target>
    </targets>
    <!-- ... -->
</nlog>
```

**Comment by snakefoot** [comment] 2022-06-22 18:54
`assembly` is not a "reserved"-word like `xsi:type`

**Comment by luigiberrettini** [comment] 2022-06-22 18:56
I do not know if it is reserved, to me you can use whatever word you prefer: you just need to add it in the NLog XSD specification so that it is recognized as attribute of the `target` element.

**Comment by snakefoot** [comment] 2022-06-22 19:01
Yes that is also a possible way for making assembly-loading-hint work with xsi:type-attribute without validation-errors.

Though I prefer `xsi:type="NLog.Targets.Syslog:Syslog"` (Since NLog.config never promised to follow XSD-standard, but like the help from the tooling with validation and intellisense)

**Comment by luigiberrettini** [comment] 2022-06-22 19:04
The important thing is just to declare it in the docs, then you can even diverge a lot more from the standard.

**Comment by luigiberrettini** [comment] 2022-06-22 19:07
Still I believe that a separate attribute in the XSD Target abstract complex type would be cleaner, more efficient than splitting for parsing purposes and could allow to deprecate the extensions altogether.

**Comment by snakefoot** [comment] 2022-06-22 19:11
`<extensions>` are still needed for layout-renderers extensions when parsing NLog Layout. Having the assembly-loading-hint was just a [random idea](https://github.com/NLog/NLog/pull/4300) to make it easier for NLog-users to use NLog-target-extensions, but also a bridge to allow NLog-core-project to eject NLog-targets that was specific to Microsof Windows into their own nuget-packages.

Can now see that my initial idea was a little better (`xsi:type="sl:NLog.Targets.Syslog.Syslog"`) according to XML-standards, and it was only the suggestion from @ThomasArdal that made it break XML-standards for QName. But XSD-intellisense would still be broken

**Comment by luigiberrettini** [comment] 2022-06-22 19:14
One not so nice solution but working and complying with specs:

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:NLog.Targets.Syslog="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">
    <targets>
        <target xsi:type="NLog.Targets.Syslog:Syslog" name="syslog-tgt">
            <NLog.Targets.Syslog:layout xsi:type="SimpleLayout" text="${message}" />
            <!-- ... -->
        </target>
    </targets>
    <!-- ... -->
</nlog>
```

**Comment by luigiberrettini** [comment] 2022-06-22 19:18
> `xsi:type="sl:NLog.Targets.Syslog.Syslog"`

Considering that you want to support both extensions plus target name and no extensions plus assembly plus target name there is no solution working since target XSDs only have one or the other.

I have Syslog in mine and any change would imply me changing the name in the XSD, making the XSD NuGet package useless unless you force all target implementers to always use the full name.

**Comment by snakefoot** [comment] 2022-06-22 19:25
The idea was not to force anything, but just to make it easier to provide an assembly-loading-hint with the type-alias. 

But see that you have to navigate careful in the woods of XML and xmlns. Guess @davidgeary should stay away from using `xsi:type` with assembly-loading-hint (And stick with `<extensions>`), until a white knight arrives and clears everything up,.

Alternative replace `xsi:type="sl:Syslog, NLog.Targets.Syslog` with `type="Syslog, NLog.Targets.Syslog"`, but then loose XML-validation and XML-intellisense.
